server:
  port: 8089 # Replace with your application's port if needed

spring:
  security:
    oauth2:
      client:
        registration:
          keycloak:
            provider: keycloak
            client-id: my-client
            client-secret: zKnyHW4uw09MHfNI6uVyAQNtpFMSO2Hc
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/keycloak"
        provider:
          keycloak:
            authorization-uri: http://localhost:8080/realms/my-realm/protocol/openid-connect/auth
            token-uri: http://localhost:8080/realms/my-realm/protocol/openid-connect/token
            user-info-uri: http://localhost:8080/realms/my-realm/protocol/openid-connect/userinfo
            jwk-set-uri: http://localhost:8080/realms/my-realm/protocol/openid-connect/certs
            issuer-uri: http://localhost:8080/realms/my-realm
      resource-server:
        jwt:
          issuer-uri: http://localhost:8080/realms/my-realm
